import { EvolutionTypes } from './Types';

// Type: [name, texture, textureScale, textureOrigin, description]
export const Evolutions: Record<any, [string, string, number, [number, number], string, string]> = {
  [EvolutionTypes.Tank]: ['Tank', 'tankOverlay', 1, [0.5, 0.55], 'Bigger than the normal player and built for defense, at the cost of being slower.', 'Overpower'],
  [EvolutionTypes.Berserker]: ['Berserker', 'berserkerOverlay', 1.18, [0.47, 0.6], 'Deals heavy damage and can move around quickly, but takes more damage.', 'Rampage'],
  [EvolutionTypes.Vampire]: ['Vampire', 'vampireOverlay', 1.09, [0.5, 0.53], 'Heals itself when dealing damage to players, and comes with well-rounded stats.', 'Leech'],
  [EvolutionTypes.Knight]: ['Knight', 'knightOverlay', 1.09, [0.5, 0.53], 'Faster than the normal player and deals a bit more damage.', 'Quick Hits'],
  [EvolutionTypes.Samurai]: ['Samurai', 'samuraiOverlay', 1.09, [0.5, 0.53], 'Fast while still being tanky, harder to push around than other evolutions.', 'Iaijutsu'],
  [EvolutionTypes.Rook]: ['Rook', 'rookOverlay', 1.09, [0.5, 0.53], 'Can only move in 4 directions, but has good range, damage, and health to make up for it.', 'Castle Dash'],
  [EvolutionTypes.Stalker]: ['Stalker', 'stalkerOverlay', 1.09, [0.5, 0.53], 'Comes with good damage and health at the same time, and can quickly escape with its ability.', 'Invisiblity'],
  [EvolutionTypes.Warrior]: ['Warrior', 'warriorOverlay', 1.09, [0.5, 0.53], 'Built to act both offensively and defensively, based on the situation.', 'Siege'],
  [EvolutionTypes.Lumberjack]: ['Lumberjack', 'lumberjackOverlay', 1.09, [0.5, 0.53], 'Great for breaking chests and gathering coins, at the cost of poor fighting capabilities.', 'Scouting'],
  [EvolutionTypes.Defender]: ['Defender', 'defenderOverlay', 1.4535, [0.5, 0.53], 'Sacrifices offense for a larger, near-unkillable build.', 'Fortress'],
  [EvolutionTypes.Fighter]: ['Fighter', 'fighterOverlay', 1.2717, [0.5, 0.53], 'Moves and fights fast, gains an offensive boost when getting hit.', 'Quick Boost'],
  [EvolutionTypes.Fisherman]: ['Fisherman', 'fishermanOverlay', 1.09, [0.5, 0.53], 'Thrown swords pull enemies towards you, stops enemies from running away.', 'Melee Pull'],
  [EvolutionTypes.Archer]: ['Archer', 'archerOverlay', 1.09, [0.49, 0.5], 'Comes with good improvements to thrown swords, but has lesser melee power.', 'Full Draw'],
  [EvolutionTypes.Sniper]: ['Sniper', 'sniperOverlay', 1.4535, [0.5, 0.53], 'Can see from further away, and thrown swords travel faster and deal more damage.', 'Headshot'],
  [EvolutionTypes.SuperArcher]: ['Archergod', 'superArcherOverlay', 1.09, [0.49, 0.5], 'Thrown swords gain up to 50% more damage based on distance.', 'Throw Recharge'],
  [EvolutionTypes.Rammer]: ['Rammer', 'rammerOverlay', 1.09, [0.5, 0.53], 'INACTIVE', 'InfiniRam'],
  [EvolutionTypes.Juggernaut]: ['Juggernaut', 'juggernautOverlay', 1.09, [0.5, 0.53], 'Above-average in every aspect, but doesn\'t have an ability.', 'None'],
  [EvolutionTypes.Slasher]: ['Slasher', 'slasherOverlay', 1.2717, [0.5, 0.53], 'INACTIVE', 'Fast Slash'],
  [EvolutionTypes.Striker]: ['Striker', 'strikerOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Thunderstorm'],
  [EvolutionTypes.Plaguebearer]: ['Plaguebearer', 'plaguebearerOverlay', 1.2717, [0.5, 0.53], 'INACTIVE', 'Poison Field'],
  [EvolutionTypes.SnowWalker]: ['Snow Walker', 'snowWalkerOverlay', 1.2717, [0.5, 0.53], 'INACTIVE', 'Chill Out'],
  [EvolutionTypes.CandyWalker]: ['Candy Walker', 'candyWalkerOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Sugar Rush'],
  [EvolutionTypes.Tree]: ['Tree', 'treeOverlay', 1.6351875, [0.5, 0.53], 'INACTIVE', 'Tree Planter'],
  [EvolutionTypes.Festive]: ['Festive', 'festiveOverlay', 1.09, [0.5, 0.53], 'INACTIVE', 'Holiday Spirit'],
  [EvolutionTypes.IceSniper]: ['Ice Sniper', 'iceSniperOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Blizzard Shot'],
  [EvolutionTypes.Snowboarder]: ['Snowboarder', 'snowboarderOverlay', 1.2717, [0.5, 0.53], 'INACTIVE', 'Sliding Knockback'],
  [EvolutionTypes.Snowtrekker]: ['Snowtrekker', 'snowtrekkerOverlay', 1.2717, [0.5, 0.53], 'INACTIVE', 'Shockwave'],
  [EvolutionTypes.IceSpike]: ['Ice Spike', 'iceSpikeOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Quickfrost'],
  [EvolutionTypes.IceKing]: ['Ice King', 'iceKingOverlay', 1.816875, [0.5, 0.53], 'INACTIVE', 'Dominion'],
  [EvolutionTypes.Drifter]: ['Drifter', 'drifterOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Speedswap'],
  [EvolutionTypes.Colossal]: ['Colossal', 'colossalOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Normalize'],
  [EvolutionTypes.Medic]: ['Medic', 'medicOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Quick Heal'],
  [EvolutionTypes.Disco]: ['Disco', 'discoOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Hypnotize'],
  [EvolutionTypes.Butcher]: ['Butcher', 'butcherOverlay', 1.4535, [0.5, 0.53], 'INACTIVE', 'Bloodcharge'],
  [EvolutionTypes.Assassin]: ['Assassin', 'assassinOverlay', 1.2717, [0.5, 0.53], 'Deals 10% of the enemy\'s remaining HP as bonus damage.', 'Silencing'],
  [EvolutionTypes.Elite]: ['The Elite', 'eliteOverlay', 1.2717, [0.5, 0.53], 'Each successful hit increases damage by 15%, up to 5 times (175% max), fading out of combat.', "Sovereign's Sword"],
  [EvolutionTypes.Tracker]: ['Tracker', 'trackerOverlay', 1.2717, [0.5, 0.53], 'Changes movement speed to match the nearest enemy.', 'Radar'],
};
